### ISSUE TITLE
Allow multiple slide position

### ISSUE THREAD

**Issue by csechuan** [r0adkll/Slidr#14]
As per title, consider a case where user can slide either left or up

**Comment by r0adkll** [comment]
This functionality is already in the library, please take a look at the [Readme](https://github.com/r0adkll/Slidr#configuring) again.

**Comment by csechuan** [comment]
Ops. Sorry I mean, user can slide more than a position. The config only allows us to input a position only. Lets say I allow user to slide left, right and bottom.

**Comment by r0adkll** [comment]
aahhhh, gotcha. Unfortunately I feel that this won't be possible due to needing multiple `ViewDragHelper` objects to achieve this kind of functionality and that they will probably start colliding and conflicting with each other producing visual artifacts.

Also, this kind of functionality is a bit out of scope for what I intended for this project so it is unlikely that I will pursue implementing this. However, you are more than welcome to fork and try to implement it yourself.

**Comment by csechuan** [comment]
I see. I dont think you need multiple ViewDragHelper. ViewDragHelper has EDGE_ALL flag. The only thing need to worry is the callback right?

**Comment by r0adkll** [comment]
Yah, I suppose its possible if you ignore the clamp methods.
