### ISSUE TITLE
hope to support fragment

### ISSUE THREAD

**Issue by wenjiahui** [r0adkll/Slidr#3]

**Comment by r0adkll** [comment]
There is no planned support for Fragments since the purpose of this library was to inject a view layer that takes advantage of the [ViewDragHelper.java](https://developer.android.com/reference/android/support/v4/widget/ViewDragHelper.html) class between the window decor view and an Activity's content view to enable this slide-to-dismiss pattern very easily. If you want this kind of support for fragments you can take a look at how I implement the above class [here](https://github.com/r0adkll/Slidr/blob/master/library/src/main/java/com/r0adkll/slidr/widget/SliderPanel.java) and implement it yourself for whatever fragment container view you are using.
